CREATE TABLE member (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(100) NOT NULL,
  nickname VARCHAR(30) NOT NULL,
  grade VARCHAR(20) NOT NULL DEFAULT 'BABY',
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  role VARCHAR(20) NOT NULL DEFAULT 'USER',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE member_profile (
  member_id BIGINT PRIMARY KEY,
  skin_type VARCHAR(20) NULL,          -- DRY|OILY|COMBINATION|SENSITIVE
  concerns VARCHAR(200) NULL,          -- 콤마 구분: PORE,TROUBLE,WRINKLE,DARK_SPOT
  age_band VARCHAR(10) NULL,           -- 10s|20s|30s|40s|50s+
  CONSTRAINT fk_profile_member FOREIGN KEY (member_id) REFERENCES member(id)
);
CREATE TABLE address (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  member_id BIGINT NOT NULL,
  receiver VARCHAR(30) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  zipcode VARCHAR(10) NOT NULL,
  address1 VARCHAR(200) NOT NULL,
  address2 VARCHAR(200) NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  is_default TINYINT(1) NOT NULL DEFAULT 0,
  CONSTRAINT fk_address_member FOREIGN KEY (member_id) REFERENCES member(id)
);
CREATE TABLE refresh_token (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  member_id BIGINT NOT NULL,
  token_hash VARCHAR(64) NOT NULL UNIQUE,
  expires_at DATETIME NOT NULL,
  CONSTRAINT fk_rt_member FOREIGN KEY (member_id) REFERENCES member(id)
);
